version: '3'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    command:
      [
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
        "--scheme",
        "http"
      ]
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-openai,backup-filesystem'
      CLUSTER_HOSTNAME: 'node1'
      BACKUP_FILESYSTEM_PATH: '/tmp/backups'
    volumes:
      - ./backups:/tmp/backups
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data: